/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "DELAY_interface.h"
#include "GPIO_interface.h"
#include "RCC_interface.h"

int main(void)
{
	MRCC_voidInitSystemClock();
	MRCC_voidEnableClock(AHB1_BUS, _PERIPHERAL_EN_GPIOA);
	MRCC_voidEnableClock(AHB1_BUS, _PERIPHERAL_EN_GPIOB);
	MRCC_voidEnableClock(AHB1_BUS, _PERIPHERAL_EN_GPIOC);
	for(u8 L_u8Counter =0 ; L_u8Counter <= 15; L_u8Counter++ )
	{
		MGPIO_voidSetPinMode(_GPIOA_PORT, L_u8Counter, _MODE_OUTPUT);
		MGPIO_voidSetPinOutPutType(_GPIOA_PORT, L_u8Counter, _OUTPUT_TYPE_PUSH_PULL);
		MGPIO_voidSetPinOutSpeed(_GPIOA_PORT, L_u8Counter, _OUTPUT_SPEED_MEDUIM);
		MGPIO_voidSetPullType(_GPIOA_PORT, L_u8Counter, _PULL_OFF);
	}
	while(1)
	{
		for(u8 L_u8Counter =0 ; L_u8Counter <= 15; L_u8Counter++ )
		{
			MGPIO_voidWriteData(_GPIOA_PORT, L_u8Counter, _HIGH);
			Delay_voidMsIn16MHz(100);
			MGPIO_voidWriteData(_GPIOA_PORT, L_u8Counter, _LOW);
		}
	}
}
